version: '3'

services:
  backend-rails:
    build: ./backend
    container_name: Backend-Rails
    restart: unless-stopped
    volumes:
      - ./backend:/app/backend
    ports:
      - '5050:5050'
    command: 'bundle exec rails s -p 5050 -b "0.0.0.0"'
    stdin_open: true
    tty: true
  
  frontend-react:
    image: 'node:10-alpine'
    container_name: Frontend-React
    restart: unless-stopped
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    command: 'yarn start'
    stdin_open: true 